openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /auth/create_user:
    post:
      security:
        - bearerAuth: []
      tags:
        - Autorizacion
      operationId: crearUsuario
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - user
                - lastName
                - name
                - email
                - pwd
                - rol
              properties:
                user:
                  type: string
                  example: johnDoe97
                name:
                  type: string
                  example: John
                lastName:
                  type: string
                  example: Doe
                email:
                  type: string
                  example: john@doe.com
                pwd:
                  type: string
                  example: johnisgreat97!.
                rol:
                  enum: ['ADMIN', 'CLIENT', 'SALES_REP']
                  type: string
                  example: ADMIN
                
      summary: Endpoint para registrar empleados al sistema o clientes, difieren solamente en roles
      responses:
        '201':
          description: |-
            El usuario fue creado correctamente
          content:
            application/json:
              examples: 
                Success:
                  value:
                    {
                      "ok": true,
                      "requestId": "12345",
                      "msg": "El usuario fue creado correctamente"
                    }
        '409':
          description: |-
            Ya existe un usuario que comparte datos unicos en la base de datos
          content:
            application/json: 
              examples: 
                Duplicate User:
                  value:
                    {
                      "ok": false,
                      "requestId": "12345",
                      "msg": "Este usuario ya existe en nuestra base de datos!"
                    }
        '500':
          description: |-
            Error interno de servidor
          content:
            application/json: 
              examples: 
                Internal Server Error:
                  value:
                    {
                      "ok": false,
                      "requestId": "12345",
                      "msg": "Error interno de servidor!"
                    }
  /auth/login:
    post:
      tags:
        - Autorizacion
      operationId: loginUsuario
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - user
                - pwd
              properties:
                user:
                  type: string
                  example: johnDoe97
                pwd:
                  type: string
                  example: johnisgreat97!.  
      summary: Endpoint para autenticar usuarios
      responses:
        '200':
          description: |-
            El inicio de sesion fue exitoso
          content:
            application/json:
              examples: 
                Success:
                  value:
                    {
                      "ok": true,
                      "requestId": "12345",
                      "payload": {
                        "uid": "6789",
                        "user": "johnDoe97",
                        "token": "token",
                        "rol": "ADMIN"
                      }
                    }
        '500':
          description: |-
            Error interno de servidor
          content:
            application/json: 
              examples: 
                Internal Server Error:
                  value:
                    {
                      "ok": false,
                      "requestId": "12345",
                      "msg": "Error interno de servidor!"
                    }
  /auth/renew:
    get:
      security:
        - bearerAuth: []
      tags:
        - Autorizacion
      operationId: revalidarToken
      summary: Endpoint para renovar el token de autenticacion
      responses:
        '200':
          description: |-
            La renovacion de sesion fue exitosa
          content:
            application/json:
              examples: 
                Success:
                  value:
                    {
                      "ok": true,
                      "requestId": "12345",
                      "payload": {
                        "uid": "6789",
                        "user": "johnDoe97",
                        "token": "token",
                        "rol": "ADMIN"
                      }
                    }
        '500':
          description: |-
            Error interno de servidor
          content:
            application/json: 
              examples: 
                Internal Server Error:
                  value:
                    {
                      "ok": false,
                      "requestId": "12345",
                      "msg": "Error interno de servidor!"
                    }   